datasource:
  type: mysql
  host: 127.0.0.1
  database: test
  username: root
  password: root
  port: 3306
  charset: utf8mb4
  collation: utf8mb4_unicode_ci
  prefix:
  deploy: 0
  rw_separate: true
  debug: true
redis: #设置redis配置
  host: 127.0.0.1
  port: 6379
  password: null
  database: 0 #默认选择0库
  prefix:
  expire: 0
cache: #缓存，驱动默认file，选择redis则其他配置起效
  driver: file
  host: 127.0.0.1
  port: 6379
  select: 2
  prefix:
  timeout: 2
  username: null
  password: null
queue: #队列,作用于异步
  db: 8 #使用的是redis，选择第8个库
rpc: #定义rpc服务
  host: 0.0.0.0 #地址
  port: 3344 #端口
  count: 4 #进程数
wechat: #正式版为 "release"，体验版为 "trial"，开发版为 "develop"
  version: develop