server: #服务
  debug: true #是否开始debug模式
  host: 127.0.0.1
  port: 11111 #服务端口
  response:
    http_code_sync: true #是否同步业务code
profile: #配置文件
  active: local #选择local则引用application-local.yml文件,同等develop、product...
socket: #socket服务
  port: 18888 #设置端口
auth:
  api:
    jwt_key: 8593d534bd1d39ec652c33365e703c71
    jwt_exp: 3600000
    jwt_aud: a
    jwt_iss: s
    enable_refresh_token: true
    refresh_token_exp: 3600000
    reuse_check: true
    token_position: header
    token_field: token